# Generated by Django 2.2.1 on 2019-05-15 09:31

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('engine_recalculate', 'Can start recalculation of recommendations')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
