# Generated by Django 2.2.1 on 2019-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('engine_recalculate', 'Can start recalculation of recommendations')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
