# Generated by Django 2.2.1 on 2019-05-24 09:46

from django.db import migrations, models
import django.db.models.deletion
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190521_1148'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='route',
            name='web_route_start_i_bf40bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='web_route_end_id_5a0c95_idx',
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=salesforce.fields.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='web.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='owner_id',
            field=models.CharField(default='0051i000001NHLCAA4', max_length=18),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['start', 'end'], name='web_route_start_i_f8ab67_idx'),
        ),
    ]
