# Generated by Django 2.2.1 on 2019-05-09 12:58

from django.db import migrations, models
import django.db.models.deletion
import heroku_connect.db.models.base
import heroku_connect.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190509_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', heroku_connect.db.models.fields.ID(db_column='sfid', db_index=True, editable=False, max_length=18, null=True, sf_field_name='Id', unique=True, upsert=False)),
                ('system_mod_stamp', heroku_connect.db.models.fields.DateTime(db_column='systemmodstamp', db_index=True, null=True, sf_field_name='SystemModstamp', upsert=False)),
                ('is_deleted', heroku_connect.db.models.fields.Checkbox(db_column='isdeleted', sf_field_name='IsDeleted', upsert=False)),
                ('_hc_lastop', models.CharField(editable=False, help_text='Indicates the last sync operation Heroku Connect performed on the record', max_length=32, null=True)),
                ('_hc_err', models.TextField(editable=False, help_text='If the last sync operation by Heroku Connect resulted in an error then this column will contain a JSON object containing more information about the error', max_length=1024, null=True)),
                ('name', heroku_connect.db.models.fields.Text(db_column='name', max_length=255, null=True, sf_field_name='Name', upsert=False)),
                ('active', heroku_connect.db.models.fields.Picklist(choices=[('Yes', 'Yes'), ('No', 'No')], db_column='active__c', max_length=255, null=True, sf_field_name='Active__c', upsert=False)),
                ('rating', heroku_connect.db.models.fields.Picklist(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], db_column='rating', max_length=255, null=True, sf_field_name='Rating', upsert=False)),
                ('numEmployees', heroku_connect.db.models.fields.Number(db_column='numberofemployees', decimal_places=0, max_digits=8, null=True, sf_field_name='NumberOfEmployees', upsert=False)),
            ],
            options={
                'db_table': 'salesforce"."account',
                'managed': False,
            },
            bases=(heroku_connect.db.models.base._HerokuConnectSnitchMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', heroku_connect.db.models.fields.ID(db_column='sfid', db_index=True, editable=False, max_length=18, null=True, sf_field_name='Id', unique=True, upsert=False)),
                ('system_mod_stamp', heroku_connect.db.models.fields.DateTime(db_column='systemmodstamp', db_index=True, null=True, sf_field_name='SystemModstamp', upsert=False)),
                ('_hc_lastop', models.CharField(editable=False, help_text='Indicates the last sync operation Heroku Connect performed on the record', max_length=32, null=True)),
                ('_hc_err', models.TextField(editable=False, help_text='If the last sync operation by Heroku Connect resulted in an error then this column will contain a JSON object containing more information about the error', max_length=1024, null=True)),
                ('username', heroku_connect.db.models.fields.Text(db_column='username', max_length=80, null=True, sf_field_name='Username', upsert=False)),
                ('email', heroku_connect.db.models.fields.Email(db_column='email', max_length=80, null=True, sf_field_name='Email', upsert=False)),
            ],
            options={
                'db_table': 'salesforce"."user',
                'managed': False,
            },
            bases=(heroku_connect.db.models.base._HerokuConnectSnitchMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason1', models.CharField(max_length=50)),
                ('reason2', models.CharField(max_length=50)),
                ('reason3', models.CharField(max_length=50)),
                ('account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='web.Account', to_field='sf_id')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='web.User', to_field='sf_id')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
