# Generated by Django 2.2.1 on 2019-06-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190525_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='account_id',
            new_name='what_id',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='what_type',
            field=models.CharField(default='account', max_length=50),
            preserve_default=False,
        ),
    ]
