# Generated by Django 2.2.1 on 2019-05-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_engine_opportunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engine',
            options={'default_permissions': (), 'managed': False, 'permissions': [('recalculate', "Can start a recalculation of a user's recommendations")]},
        ),
    ]
