# Generated by Django 2.2.1 on 2019-06-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190611_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='what_id',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='account_id',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='contact_id',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='lead_id',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='opportunity_id',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='what_type',
            field=models.CharField(choices=[('account', 'Account'), ('opportunity', 'Opportunity'), ('lead', 'Lead'), ('contact', 'Contact')], max_length=11),
        ),
    ]
