# Generated by Django 2.2.1 on 2019-06-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190611_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='lead_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='opportunity_id',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='what_id',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
