# Generated by Django 2.2.1 on 2019-06-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190619_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='title',
            field=models.CharField(default='This record looks promising', max_length=50),
            preserve_default=False,
        ),
    ]
