# Generated by Django 2.2.1 on 2019-06-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190620_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='loc_id',
            new_name='location',
        ),
    ]
