# Generated by Django 2.2.1 on 2019-06-20 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190620_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 9, 19, 29, 565073)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='service_time',
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 10, 20, 4, 269765)),
            preserve_default=False,
        ),
    ]
