# Generated by Django 2.2.1 on 2019-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190620_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='reason1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason3',
            field=models.CharField(max_length=60),
        ),
    ]
